paths:
  /api/users/:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        "200":
          description: Users were correctly fetched from DB
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500":
          description: Internal error while retrieving users from DB
    post:
      tags:
        - Users
      summary: Registers a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User was correctly created and posted to DB
        "400":
          description: Bad request, please check the user data provided
        "500":
          description: Internal error while posting user to DB
  /api/users/{id}:
    get:
      tags:
        - Users
      summary: Get a user by ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the user to retrieve
          content:
            application/json:
              schema:
                type:
                  $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Selected user was correctly fetched from DB
        "403":
          description: Forbidden. User must be logged to access API data
        "404":
          description: Selected user was not found
        "500":
          description: Internal error while retrieving user from DB
    delete:
      tags:
        - Users
      summary: Deletes a user
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the user to delete
          schema:
            type: string
      responses:
        "200":
          description: Selected user was correctly deleted from DB
        "403":
          description: Forbidden. User must be logged to access API data
        "404":
          description: Selected user was not found
        "500":
          description: Internal error while deleting selected user from DB
    put:
      tags:
        - Users
      summary: Updates a user
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the user to update
          schema:
            $type: integer
      responses:
        "200":
          description: Selected user was correctly updated in DB
        "403":
          description: Forbidden. User must be logged to access API data
        "404":
          description: Selected user was not found
        "500":
          description: Internal error while updating selected user in DB
